version: 2.1

jobs:
  build-and-test-backend:
    working_directory: ~/zds-site
    docker:
      - image: cimg/node:18.12.0
    steps:
      - checkout
      - run:
          name: install dependencies
          command: cd ../backend/test-backend && npm install

      - run:
          name: run ../backend/test-backend && npm run test
workflows:
  sample:
    jobs:
      - build-and-test-backend
