version: 2.1

jobs:
  build-and-test-backend:
    docker:
      - image: cimg/node:18.12.0
    steps:
      - checkout
      - run:
          name: install dependencies
          command: cd test-backend && npm install
      - run:
          name: run tests
          command: cd test-backend && npm run test
          
workflows:
  sample:
    jobs:
      - build-and-test-backend
