version: 2.1
jobs:
  build-and-test-backend:
    working_directory: ~/ac_posystem/backend
    docker:
      - image: cimg/node:18.12.0
    steps:
      - checkout
      - run:
          name: Current Directory
          command: pwd
      - run:
          name: install dependencies
          command: npm install
      
workflows:
  sample:
    jobs:
      - build-and-test-backend
