version: 2.1
jobs:
  build-and-test-backend:
    working_directory: ~/AchiversCodeRoot/ac_posystem/backend
    docker:
      - image: cimg/node:18.12.0
    steps:
      - checkout:
          path: ~/AchiversCodeRoot
      - run:
          name: Current Directory
          command: pwd
      - run:
          name: list all files in current Directory
          command: ls
      - run:
          name: install dependencies
          command: npm install
      
workflows:
  sample:
    jobs:
      - build-and-test-backend
