version: 2.1
jobs:
  build-and-test-backend:
    working_directory: ~/ac_posystem
    docker:
      - image: cimg/node:18.12.0
    steps:
      - checkout
        
      - run:
          name: install dependencies
          command: cd test-backend && npm install
      
workflows:
  sample:
    jobs:
      - build-and-test-backend
