version: 2.1

jobs:
  build-and-test-javascript:
    docker:
      - image: cimg/node:14.20.0
    steps:
      - checkout
      - run:
          name: install dependencies
          command: cd ac_posystem/backend && npm install

      - run:
          name: run test
          command: cd ac_posystem/backend/test && npm run test
workflows:
  sample:
    jobs:
      - build-and-test-javascript
